### ISSUE TITLE
How to load a DA object from file?

### ISSUE THREAD

**Issue by zhjsun** [dacelib/dace#2]
I know that we can print a DA object into a file by using the output operator "<<".

I'm wondering is there any way that we can load the DA object from the output file, e.g. with the input operator ">>".

If this is possible, I think it will be very useful in many cases. For example, we can compute the DA object and print it into a file first,  next time we will load it directly and evaluate the polynomials without computing the DA object again.

**Comment by abgandar** [comment]
Indeed DA objects can be read from a stream using the stream extraction operator >>. For example:

```
#include "DA/dace.h"
#include <fstream>

using namespace std;
using namespace DACE;

int main( void )
{   
    DA::init( 20, 1 );
    DA x = DA::random(1.0);
    DA y = sin(x);

    // output x and y to file
    ofstream os("test.dat", ofstream::binary);	// Windows requires binary flag if this stream is used to write binary DA representations ("stored DAs")
    os << x             // output DA x as a human readable ASCII representation
       << storedDA(y);  // and DA y as a compact binary representation
    os.close();

    // read values back
    DA xx, yy;
    ifstream is("test.dat", ifstream::binary);	// same here: Windows needs to be told explicitly about binary files
    is >> xx >> yy; // same stream extraction operator handles both binary and ASCII for reading
    is.close();

    // show differences
    cout << "Difference between x and read value:\n" << x-xx << endl;
    cout << "Difference between y and read value:\n" << y-yy << endl;    
}
```

Note the two ways of writing a DA: human readable and binary (a "stored DA"). Binary is lossless and smaller, but not readable except using the DACE library. ASCII is human readable but potentially lossy due to conversion between binary and decimal representation.
The same read operation can read either one from a file. 

When reading multiple DAs, any additional output you write to the file between two DAs (e.g. empty lines to separate text output) will cause the library to fail reading back DAs unless you also consume (=read or skip over) the extra output before trying to read another DA.
