### ISSUE TITLE
Problem running Tutorial1/Example7

### ISSUE THREAD

**Issue by GBZH** [dacelib/dace#43]
Hello,

I have downloaded your DACE package yesterday and successfully compiled it on Ubuntu 22.04.
The tutorial examples compiled as well (except Example11DARK78.cpp which is ignored), but when running Tutorial1/Example7, I get the following message:

`Evaluate sombrero function

terminate called after throwing an instance of 'DACE::DACEException'
  what():  daceRoot: Zero-th root does not exist (ID: 645)
Aborted (core dumped)
`
I am wondering if this could be linked to the warning message appearing when compiling the whole package:

`[ 96%] Built target c_core_contrib
.../dace/interfaces/cxx/DA.cpp: In static member function ‘static void DACE::DA::init(unsigned int, unsigned int)’:
.../dace/interfaces/cxx/DA.cpp:69:27: warning: catching polymorphic type ‘class DACE::DACEException’ by value [-Wcatch-value=]
   69 |     } catch(DACEException ex) {
      |                           ^~
.../dace/interfaces/cxx/DA.cpp: In static member function ‘static void DACE::DA::init(unsigned int, unsigned int)’:
.../dace/interfaces/cxx/DA.cpp:69:27: warning: catching polymorphic type ‘class DACE::DACEException’ by value [-Wcatch-value=]
   69 |     } catch(DACEException ex) {
      |                           ^~
[ 96%] Built target c_core
`
All other executables  run w/o error messages.

Thanks a lot for any help,

Gilles

**Comment by mmassari1974** [comment]
Hi Gilles, 
this is not a compilation error, it is the expected behavior of example 7. Mathematically the Sombrero function is not defined in (0,0). Therefore, when you try to evaluate it the DACE library rises an exception, which in the very simple code of the example 7 is not managed. Try adding a constant to one of the element of x and the code will correctly evaluate the sombrero function.
Closing the issue as this is not an error in the code.
Mauro.
